services:
  - type: web
    name: dr-krishna-induvasi-hospital
    runtime: node
    plan: free
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: ADMIN_KEY
        generateValue: true
    autoDeploy: true
